services:
  - type: web
    name: earning-link-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LINKSTERR_API_KEY
        sync: false
      - key: CHANNEL_USERNAME
        value: nr_hackz
      - key: PYTHON_VERSION
        value: 3.11.9
